### ISSUE TITLE
Output is hard to interpret

### ISSUE THREAD

**Issue by yujue-wang** [hinfsynz/EZName#1]
✘ yujue.wang@MBP-0919  ~/python/EZName   master  Python3 EZName.py -s 王 -g M -y 2020 -m 3 -d 30
[*] 出生日期：2020年3月30日, 0时
[*] 五行属性：水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 1时
[*] 五行属性：水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 2时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 3时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 4时
[*] 五行属性：水, 金, 木

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 5时
[*] 五行属性：水, 金, 木

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 6时
[*] 五行属性：水, 金, 木

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 7时
[*] 五行属性：水, 金, 木

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 8时
[*] 五行属性：土, 水, 金, 木

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 9时
[*] 五行属性：土, 水, 金, 木

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 10时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 11时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 12时
[*] 五行属性：火, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 13时
[*] 五行属性：火, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 14时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 15时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 16时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 17时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 18时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 19时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 20时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 21时
[*] 五行属性：土, 水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 22时
[*] 五行属性：水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5
[*] 出生日期：2020年3月30日, 23时
[*] 五行属性：水, 金

no. of matches = 1
no. of matches = 2
no. of matches = 3
no. of matches = 4
no. of matches = 5

**Comment by hinfsynz** [comment]
issue fixed in commit #b2c21ea
Below is the test output:

[hadoop@ip-10-0-4-139 EZName]$ python3 EZName.py -s 张 -g M -m 5 -d 7 -y 2020 -H 10 -n True
[*] 出生日期：2020年5月7日, 10时
[*] 五行属性：金, 火

Getting score for name: 张飙乎 from http://1518.com...
score is 90
no. of matches = 1
Getting score for name: 张万民 from http://1518.com...
score is 96
no. of matches = 2
Getting score for name: 张地方 from http://1518.com...
score is 64
Score is below the cutoff value. Continue searching...
Getting score for name: 张安以 from http://1518.com...
score is 96
no. of matches = 3
Getting score for name: 张无故 from http://1518.com...
score is 92
no. of matches = 4
Getting score for name: 张固有 from http://1518.com...
score is 58
Score is below the cutoff value. Continue searching...
Getting score for name: 张杲杲 from http://1518.com...
score is 54
Score is below the cutoff value. Continue searching...
Getting score for name: 张革孽 from http://1518.com...
score is 55
Score is below the cutoff value. Continue searching...
Getting score for name: 张不服 from http://1518.com...
score is 72
no. of matches = 5
Searching Done!
Name, Pinyin, Score(Optional)
张万民, wan-min, 96
张安以, an-yi, 96
张无故, wu-gu, 92
张飙乎, biao-hu, 90
张不服, bu-fu, 72
